// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/MASH.h"
#include <Rcpp.h>

using namespace Rcpp;

// util_PfSIoneHistory
void util_PfSIoneHistory(const Rcpp::List& historyIxH, const NumericVector& timeBins, NumericMatrix timeSeries);
RcppExport SEXP MASH_util_PfSIoneHistory(SEXP historyIxHSEXP, SEXP timeBinsSEXP, SEXP timeSeriesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type historyIxH(historyIxHSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type timeBins(timeBinsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type timeSeries(timeSeriesSEXP);
    util_PfSIoneHistory(historyIxH, timeBins, timeSeries);
    return R_NilValue;
END_RCPP
}
// HumanEventQ__ctor
MASH::HumanEventQ HumanEventQ__ctor(int initQ);
RcppExport SEXP MASH_HumanEventQ__ctor(SEXP initQSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type initQ(initQSEXP);
    rcpp_result_gen = Rcpp::wrap(HumanEventQ__ctor(initQ));
    return rcpp_result_gen;
END_RCPP
}
// HumanEventQ__firstEvent
Rcpp::List HumanEventQ__firstEvent(MASH::RcppR6::RcppR6<MASH::HumanEventQ> obj_);
RcppExport SEXP MASH_HumanEventQ__firstEvent(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::HumanEventQ> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(HumanEventQ__firstEvent(obj_));
    return rcpp_result_gen;
END_RCPP
}
// HumanEventQ__firstTime
int HumanEventQ__firstTime(MASH::RcppR6::RcppR6<MASH::HumanEventQ> obj_);
RcppExport SEXP MASH_HumanEventQ__firstTime(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::HumanEventQ> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(HumanEventQ__firstTime(obj_));
    return rcpp_result_gen;
END_RCPP
}
// HumanEventQ__rmFirstEventFromQ
void HumanEventQ__rmFirstEventFromQ(MASH::RcppR6::RcppR6<MASH::HumanEventQ> obj_);
RcppExport SEXP MASH_HumanEventQ__rmFirstEventFromQ(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::HumanEventQ> >::type obj_(obj_SEXP);
    HumanEventQ__rmFirstEventFromQ(obj_);
    return R_NilValue;
END_RCPP
}
// HumanEventQ__rmTagFromQ
void HumanEventQ__rmTagFromQ(MASH::RcppR6::RcppR6<MASH::HumanEventQ> obj_, std::string tag);
RcppExport SEXP MASH_HumanEventQ__rmTagFromQ(SEXP obj_SEXP, SEXP tagSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::HumanEventQ> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< std::string >::type tag(tagSEXP);
    HumanEventQ__rmTagFromQ(obj_, tag);
    return R_NilValue;
END_RCPP
}
// HumanEventQ__get_queueN
int HumanEventQ__get_queueN(MASH::RcppR6::RcppR6<MASH::HumanEventQ> obj_);
RcppExport SEXP MASH_HumanEventQ__get_queueN(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::HumanEventQ> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(HumanEventQ__get_queueN(obj_));
    return rcpp_result_gen;
END_RCPP
}
// HumanEventQ__addEvent2Q
void HumanEventQ__addEvent2Q(MASH::RcppR6::RcppR6<MASH::HumanEventQ> obj_, Rcpp::List event);
RcppExport SEXP MASH_HumanEventQ__addEvent2Q(SEXP obj_SEXP, SEXP eventSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::HumanEventQ> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type event(eventSEXP);
    HumanEventQ__addEvent2Q(obj_, event);
    return R_NilValue;
END_RCPP
}
// HumanEventQ__get_EventQ
Rcpp::List HumanEventQ__get_EventQ(MASH::RcppR6::RcppR6<MASH::HumanEventQ> obj_);
RcppExport SEXP MASH_HumanEventQ__get_EventQ(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::HumanEventQ> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(HumanEventQ__get_EventQ(obj_));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"MASH_util_PfSIoneHistory", (DL_FUNC) &MASH_util_PfSIoneHistory, 3},
    {"MASH_HumanEventQ__ctor", (DL_FUNC) &MASH_HumanEventQ__ctor, 1},
    {"MASH_HumanEventQ__firstEvent", (DL_FUNC) &MASH_HumanEventQ__firstEvent, 1},
    {"MASH_HumanEventQ__firstTime", (DL_FUNC) &MASH_HumanEventQ__firstTime, 1},
    {"MASH_HumanEventQ__rmFirstEventFromQ", (DL_FUNC) &MASH_HumanEventQ__rmFirstEventFromQ, 1},
    {"MASH_HumanEventQ__rmTagFromQ", (DL_FUNC) &MASH_HumanEventQ__rmTagFromQ, 2},
    {"MASH_HumanEventQ__get_queueN", (DL_FUNC) &MASH_HumanEventQ__get_queueN, 1},
    {"MASH_HumanEventQ__addEvent2Q", (DL_FUNC) &MASH_HumanEventQ__addEvent2Q, 2},
    {"MASH_HumanEventQ__get_EventQ", (DL_FUNC) &MASH_HumanEventQ__get_EventQ, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_MASH(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
