// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// util_PfSIoneHistory
void util_PfSIoneHistory(const Rcpp::List& historyIxH, const NumericVector& timeBins, NumericMatrix timeSeries);
RcppExport SEXP MASH_util_PfSIoneHistory(SEXP historyIxHSEXP, SEXP timeBinsSEXP, SEXP timeSeriesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type historyIxH(historyIxHSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type timeBins(timeBinsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type timeSeries(timeSeriesSEXP);
    util_PfSIoneHistory(historyIxH, timeBins, timeSeries);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"MASH_util_PfSIoneHistory", (DL_FUNC) &MASH_util_PfSIoneHistory, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_MASH(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
