# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' PfSI: Write One Human History
#'
#' This is a C++ helper function for \code{\link{util_PfSIHistory}}
#'
#' @param historyIxH a single human history from \code{Human$get_History()}
#' @param timeBins vector of time bins (state transition times)
#' @param timeSeries matrix of occupancy vectors
#'
#'
#' @export
util_PfSIoneHistory <- function(historyIxH, timeBins, timeSeries) {
    invisible(.Call('MASH_util_PfSIoneHistory', PACKAGE = 'MASH', historyIxH, timeBins, timeSeries))
}

