## Generated by RcppR6: do not edit by hand
## Version: 0.2.4
## Hash: 153ff8fcdc5c4ed6be7f552fad7006ba

##' @importFrom Rcpp evalCpp
##' @importFrom R6 R6Class
##' @useDynLib MASH
NULL

##' A class for queueing human events. Header file defined [here](https://github.com/slwu89/RcppQueues/blob/master/inst/include/RcppQueues/HumanEventQ.hpp) and `RcppR6` export handled [here](https://github.com/slwu89/RcppQueues/blob/master/inst/HumanEventQ.yml). Bound to \code{Human$EventQueue} in class \code{\link{Human}}
##' @title Human Event Queue
##' @param initQ reserve memory for \code{initQ} number of events
##' @section Methods:
##'   * firstEvent: return first event in queue as named R list
##'   * firstTime: return 'tEvent' slot in first event in queue
##'   * rmFirstEventFromQ: remove first event in queue and update \code{queueN}
##'   * rmTagFromQ(const std::string &tag): remove all events with certain tag from queue and update \code{queueN}
##'   * get_queueN: return \code{queueN}
##'   * get_EventQ: return entire \code{EventQ} as R list
##'   * addEvent2Q(Rcpp::List event): add a list to the \code{EventQ} in correct time order and update \code{queueN}
##' @section Fields:
##'   * EventQ: \code{std::vector<Rcpp::List>}
##'   * queueN: integer value of size of queue.
##' @md
##' @export
`HumanEventQ` <- function(initQ=100) {
  HumanEventQ__ctor(initQ)
}
.R6_HumanEventQ <-
  R6::R6Class(
    "HumanEventQ",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      firstEvent = function() {
        HumanEventQ__firstEvent(self)
      },
      firstTime = function() {
        HumanEventQ__firstTime(self)
      },
      rmFirstEventFromQ = function() {
        HumanEventQ__rmFirstEventFromQ(self)
      },
      rmTagFromQ = function(tag) {
        HumanEventQ__rmTagFromQ(self, tag)
      },
      get_queueN = function() {
        HumanEventQ__get_queueN(self)
      },
      addEvent2Q = function(event) {
        HumanEventQ__addEvent2Q(self, event)
      },
      get_EventQ = function() {
        HumanEventQ__get_EventQ(self)
      }),
    active=list())

##' A class for recording generic histories comprised of event times (double precision floats) and events (strings).
##' @title Generic History
##' @param N reserve memory for \code{N} number of events
##' @section Methods:
##'   * track_history: record an event from arguments 'tEvent' (double) and 'event' (string)
##'   * get_history: return history as a named list
##' @section Fields:
##'   * eventT: \code{std::vector<double>}
##'   * events: \code{std::vector<std::string>}
##' @md
##' @export
`HistoryGeneric` <- function(N=100) {
  HistoryGeneric__ctor(N)
}
.R6_HistoryGeneric <-
  R6::R6Class(
    "HistoryGeneric",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      track_history = function(tEvent, event) {
        HistoryGeneric__track_history(self, tEvent, event)
      },
      get_history = function() {
        HistoryGeneric__get_history(self)
      }),
    active=list())

##' A class for recording travel histories comprised of event times (double precision floats) and locations (integers).
##' @title Travel History
##' @param N reserve memory for \code{N} number of events
##' @section Methods:
##'   * track_travel: record an event from arguments 'tEvent' (double) and 'event' (string)
##'   * get_travelHistory: return history as a named list
##' @section Fields:
##'   * tTravel: \code{std::vector<double>}
##'   * locationH: \code{std::vector<int>}
##' @md
##' @export
`HistoryTravel` <- function(N=100) {
  HistoryTravel__ctor(N)
}
.R6_HistoryTravel <-
  R6::R6Class(
    "HistoryTravel",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      track_travel = function(tTravel, locationH) {
        HistoryTravel__track_travel(self, tTravel, locationH)
      },
      get_travelHistory = function() {
        HistoryTravel__get_travelHistory(self)
      }),
    active=list())

##' A class for storing parameters and state variables of human-stage PfSI infections.
##' @title PfSI Human Stage Pathogen Class
##' @param PfID_init PfID derived from the tile level PfPedigree
##' @param tInf_init time of current infection (successful mosquito to human transmission event)
##' @param b_init infected mosquito to human transmission efficiency
##' @param c_init infected human to mosquito transmission efficiency
##' @param damID_init female gametocyte 'mother'
##' @param sireID_init male gametocyte 'father'
##' @param infected_init infection status
##' @param chemoprophylaxis_init chemoprophylaxis protection status
##' @section Methods:
##'   * firstEvent: return first event in queue as named R list
##'   * firstTime: return 'tEvent' slot in first event in queue
##'   * rmFirstEventFromQ: remove first event in queue and update \code{queueN}
##'   * rmTagFromQ(const std::string &tag): remove all events with certain tag from queue and update \code{queueN}
##'   * get_queueN: return \code{queueN}
##'   * get_EventQ: return entire \code{EventQ} as R list
##'   * addEvent2Q(Rcpp::List event): add a list to the \code{EventQ} in correct time order and update \code{queueN}
##' @section Fields:
##'   * EventQ: \code{std::vector<Rcpp::List>}
##'   * queueN: integer value of size of queue.
##' @md
##' @export
`humanPfSIcpp` <- function(PfID_init, tInf_init=-1, b_init=0.55, c_init=0.15, damID_init=-1, sireID_init=-1, infected_init=FALSE, chemoprophylaxis_init=FALSE) {
  humanPfSIcpp__ctor(PfID_init, tInf_init, b_init, c_init, damID_init, sireID_init, infected_init, chemoprophylaxis_init)
}
.R6_humanPfSIcpp <-
  R6::R6Class(
    "humanPfSIcpp",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      track_history = function(tEvent, event) {
        humanPfSIcpp__track_history(self, tEvent, event)
      },
      get_history = function() {
        humanPfSIcpp__get_history(self)
      }),
    active=list())


