# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' PfSI: Write One Human History
#'
#' This is a C++ helper function for \code{\link{util_PfSIHistory}}
#'
#' @param historyIxH a single human history from \code{Human$get_History()}
#' @param timeBins vector of time bins (state transition times)
#' @param timeSeries matrix of occupancy vectors
#'
#'
#' @export
util_PfSIoneHistory <- function(historyIxH, timeBins, timeSeries) {
    invisible(.Call('MASH_util_PfSIoneHistory', PACKAGE = 'MASH', historyIxH, timeBins, timeSeries))
}

HumanEventQ__ctor <- function(initQ) {
    .Call('MASH_HumanEventQ__ctor', PACKAGE = 'MASH', initQ)
}

HumanEventQ__firstEvent <- function(obj_) {
    .Call('MASH_HumanEventQ__firstEvent', PACKAGE = 'MASH', obj_)
}

HumanEventQ__firstTime <- function(obj_) {
    .Call('MASH_HumanEventQ__firstTime', PACKAGE = 'MASH', obj_)
}

HumanEventQ__rmFirstEventFromQ <- function(obj_) {
    invisible(.Call('MASH_HumanEventQ__rmFirstEventFromQ', PACKAGE = 'MASH', obj_))
}

HumanEventQ__rmTagFromQ <- function(obj_, tag) {
    invisible(.Call('MASH_HumanEventQ__rmTagFromQ', PACKAGE = 'MASH', obj_, tag))
}

HumanEventQ__get_queueN <- function(obj_) {
    .Call('MASH_HumanEventQ__get_queueN', PACKAGE = 'MASH', obj_)
}

HumanEventQ__addEvent2Q <- function(obj_, event) {
    invisible(.Call('MASH_HumanEventQ__addEvent2Q', PACKAGE = 'MASH', obj_, event))
}

HumanEventQ__get_EventQ <- function(obj_) {
    .Call('MASH_HumanEventQ__get_EventQ', PACKAGE = 'MASH', obj_)
}

