#################################################################
#
#   MASH/MBITES
#   Pathogen Profile
#   R version
#   Sean Wu
#   January 24, 2017
#
#################################################################


#################################################################
# PfTransmission Analysis
#################################################################

# ix = which(PfTransmission$M2H == 1)[1]

#' Extract a Transmission Chain from PfTransmission
#'
#' Extract a transmission chain generated by \code{\link{trackPfTransmission}}
#'
#' @param ix index of mosquito to human transmission
extractChain <- function(ix, PfTransmission){

  initM = as.character(PfTransmission$ixM[ix])
  transmissionChain = PfTransmission[PfTransmission$ixM==initM,]

  chain = TRUE
  while(chain){

    lastEvent = transmissionChain[nrow(transmissionChain),]

    if(lastEvent$M2H){
      PfTransmission[(PfTransmission$time > lastEvent$time) & (PfTransmission$ixH == lastEvent$ixH),]
    } else {

    }


  }

}
